// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIsu2ycIYnWThHDFcyLVs1dC7mMkqUNTQ',
    appId: '1:576716495489:web:46331db571ee08e90c0b80',
    messagingSenderId: '576716495489',
    projectId: 'fusionfiesta-91509',
    authDomain: 'fusionfiesta-91509.firebaseapp.com',
    storageBucket: 'fusionfiesta-91509.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdJCRX1TG7y1m_2zZPUTBfyCvyF4rQuk',
    appId: '1:576716495489:android:f93bc7dd10f2ff320c0b80',
    messagingSenderId: '576716495489',
    projectId: 'fusionfiesta-91509',
    storageBucket: 'fusionfiesta-91509.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcPS87IUgmY6sxyoQa4iqSbBYin92wuKg',
    appId: '1:576716495489:ios:760370a3e0c674290c0b80',
    messagingSenderId: '576716495489',
    projectId: 'fusionfiesta-91509',
    storageBucket: 'fusionfiesta-91509.firebasestorage.app',
    iosBundleId: 'com.example.fusionfiesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcPS87IUgmY6sxyoQa4iqSbBYin92wuKg',
    appId: '1:576716495489:ios:760370a3e0c674290c0b80',
    messagingSenderId: '576716495489',
    projectId: 'fusionfiesta-91509',
    storageBucket: 'fusionfiesta-91509.firebasestorage.app',
    iosBundleId: 'com.example.fusionfiesta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIsu2ycIYnWThHDFcyLVs1dC7mMkqUNTQ',
    appId: '1:576716495489:web:524119e72e2d8e5e0c0b80',
    messagingSenderId: '576716495489',
    projectId: 'fusionfiesta-91509',
    authDomain: 'fusionfiesta-91509.firebaseapp.com',
    storageBucket: 'fusionfiesta-91509.firebasestorage.app',
  );
}
